version: "3.8"
services:
  database:
    container_name: database
    image: postgres
    ports:
      - "9090:9090"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=todo_listDB
      - POSTGRES_USER=mdimins
      - POSTGRES_PASSWORD=matisins
      